# Generated by Django 4.2.9 on 2024-05-24 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='countery',
            new_name='country',
        ),
    ]
